// <auto-generated />
namespace WebClinica.InfraEstrutura.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AjusteModelagemAnamnese2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AjusteModelagemAnamnese2));
        
        string IMigrationMetadata.Id
        {
            get { return "201703162115555_AjusteModelagemAnamnese2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
